### ISSUE TITLE
tronbox migrating can not use the .at(contract address)

### ISSUE THREAD

**Issue by bigopher** [tronprotocol/tron-box#63]
when writing following migratation script in tronbox， there will happen to some error. but that can work well in truffle, please check it, thanks!
let a  = await A.at('4174ca9d500f00601b8e1db69734c05e04b7b67be8');

the errors show that:
(node:3722) UnhandledPromiseRejectionWarning: TypeError: this.getContract is not a function
    at TronWrap.tronWrap._getContract (/usr/local/Cellar/node/11.2.0/lib/node_modules/tronbox/build/webpack:/packages/tronwrap/index.js:135:1)
    at /usr/local/Cellar/node/11.2.0/lib/node_modules/tronbox/build/webpack:/packages/truffle-contract/contract.js:413:1
    at new Promise (<anonymous>)
    at /usr/local/Cellar/node/11.2.0/lib/node_modules/tronbox/build/webpack:/packages/truffle-contract/contract.js:412:1
    at new Promise (<anonymous>)

**Comment by MioGreen** [comment]
@sullof do you have any recommendation on how we can do .at function right now?

**Comment by sullof** [comment]
Can you point me to some sample code to replicate the error?

**Comment by MioGreen** [comment]
@sullof I've received a new error:

(node:24235) UnhandledPromiseRejectionWarning: TypeError: code.replace is not a function
    at /usr/local/lib/node_modules/tronbox-stage/build/webpack:/packages/truffle-contract/contract.js:416:1
    at /usr/local/lib/node_modules/tronbox-stage/build/webpack:/packages/tronwrap/index.js:149:1
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by bigopher** [comment]
same the error to the description from MioGreen

**Comment by sullof** [comment]
I think the problem is that TronBox artifacts don't support `.at(address)`. If you need that, you must use TronWeb.
We could add support for .at and .new in the future. I am leaving this issue opened as a reminder.
