### ISSUE TITLE
deploy error

### ISSUE THREAD

**Issue by flyq** [tronprotocol/tron-box#71]
PS C:\Users\xing9\Documents\GitHub\Tron_Idol> tronbox migrate --reset
> Using network 'development'.
Running migration: 2_deploy_contracts.js
  Deploying Migrations...
  Migrations:
    (base58) TWNArsTTDv9ffeG2rr8st9HLv27yHBMNyy
    (hex) 41dfba4ba174dbeb69e1dff782bc0e9203d23e8f1a
  Deploying GeneScience...
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: Contract has not been deployed on the network
    at C:\Users\xing9\AppData\Roaming\npm\node_modules\tronbox\build\webpack:\packages\tronwrap\index.js:158:1
    at process._tickCallback (internal/process/next_tick.js:68:7)

PS C:\Users\xing9\Documents\GitHub\Tron_Idol> tronbox migrate --reset
> Using network 'development'.
Running migration: 2_deploy_contracts.js
  Deploying Migrations...
  Migrations:
    (base58) TJPCDtMQCE6w1QE3rArkmEnAuXvPBc12wz
    (hex) 415c4a56d666b534ba8b81873d41b5105babe44beb
  Deploying GeneScience...
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: Contract has not been deployed on the network
    at C:\Users\xing9\AppData\Roaming\npm\node_modules\tronbox\build\webpack:\packages\tronwrap\index.js:158:1
    at process._tickCallback (internal/process/next_tick.js:68:7)

PS C:\Users\xing9\Documents\GitHub\Tron_Idol> tronbox migrate --reset
> Using network 'development'.
Running migration: 2_deploy_contracts.js
  Deploying Migrations...
  Deploying GeneScience...
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: Contract has not been deployed on the network
    at C:\Users\xing9\AppData\Roaming\npm\node_modules\tronbox\build\webpack:\packages\tronwrap\index.js:158:1
    at process._tickCallback (internal/process/next_tick.js:68:7)

PS C:\Users\xing9\Documents\GitHub\Tron_Idol> tronbox migrate --reset
> Using network 'development'.
Running migration: 2_deploy_contracts.js
  Deploying Migrations...
  Migrations:
    (base58) TSk58Hd9RKVS9Uo8ST2yyvt48fdmGuwsxB
    (hex) 41b7fe28237c85400106e4dbd1e4fd80a9036ec4a6
  Deploying GeneScience...
  GeneScience:
    (base58) TDJWBp4H15zNAuLCfJjJx5NKdwhhMZABHh
    (hex) 41248ea0537c3c66d9b565f299d96d2819977ee5f9
Saving successful migration to network...
Saving artifacts...

PS C:\Users\xing9\Documents\GitHub\Tron_Idol>

I don't do anything between these operation. It failed before and succeeded at last.

**Comment by flyq** [comment]
PS C:\> tronbox version
>Tronbox v2.2.3-prev.0 (core: 4.1.13)
Solidity v0.4.24 (tron-solc)

PS C:\>
