### ISSUE TITLE
tronbox migrate --reset --network shasta msg killed

### ISSUE THREAD

**Issue by yanwankun** [tronprotocol/tron-box#86]
I tried to deploy a contract, but I am getting an error when I execute "tronbox migrate --reset --network shasta". The error message was killed. 
git clone https://github.com/sullof/metacoin-box.git
cd metacoin-box/
cd migrations/
vim tronbox.js
``````
module.exports = {
  networks: {
    shasta: {
      privateKey: '8c86e28648c71a0b42c255f941c14d35b2a10148a83ae8ae6ed8254a7a93c0f8',
      consume_user_resource_percent: 30,
      fee_limit: 100000000,
      fullNode: "https://api.shasta.trongrid.io",
      solidityNode: "https://api.shasta.trongrid.io",
      eventServer: "https://api.shasta.trongrid.io",
      network_id: "*"
    },
  }
};
``````
tronbox compile --compile-all
``````
[root@izj6c28ftc1v9t3nkz3cofz metacoin-box]# tronbox compile --compile-all
(node:3696) V8: /usr/local/lib/node_modules/tronbox/build/cli.bundled.js:171823 Invalid asm.js: Invalid member of stdlib
(node:3696) V8: /usr/local/lib/node_modules/tronbox/build/cli.bundled.js:171793 Invalid asm.js: Invalid member of stdlib
(node:3696) V8: /usr/local/lib/node_modules/tronbox/build/cli.bundled.js:84011 Invalid asm.js: Invalid member of stdlib
Compiling ./contracts/ConvertLib.sol...
Compiling ./contracts/MetaCoin.sol...
Compiling ./contracts/Migrations.sol...
Writing artifacts to ./build/contracts
``````
tronbox migrate --reset --network shasta
``````
[root@izj6c28ftc1v9t3nkz3cofz metacoin-box]# tronbox migrate --network shasta
Killed
``````
My operating system is Alibaba Cloud centos 7, 2 core cpu
Can you give me some advice?

**Comment by yanwankun** [comment]
``````
[root@izj6c28ftc1v9t3nkz3cofz metacoin-box]# npm -v
6.5.0
[root@izj6c28ftc1v9t3nkz3cofz metacoin-box]# node -v
v11.9.0
[root@izj6c28ftc1v9t3nkz3cofz metacoin-box]# uname -r
3.10.0-957.1.3.el7.x86_64
``````

**Comment by yanwankun** [comment]
I have a new discovery
``````
[root@izj6c28ftc1v9t3nkz3cofz metacoin-box]# sudo tronbox migrate --network shasta
/usr/lib/node_modules/tronbox/build/cli.bundled.js:1733
  tronWrap._getNetworkInfo = async function () {
                                   ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)


the code is
  1733   tronWrap._getNetworkInfo = async function () {
  1734     let info = {
  1735       javaTronVersion: '<3.2.2',
  1736       compilerVersion: '1'
  1737     }
  1738     try {
  1739       const [proposals, nodeInfo] = await Promise.all([
  1740         tronWrap.trx.getChainParameters(),
  1741         tronWrap.trx.getNodeInfo()
  1742       ])
  1743 
  1744       for(let proposal of proposals) {
  1745         if(proposal.key === 'getAllowTvmTransferTrc10') {
  1746           if(proposal.value) {
  1747             info.compilerVersion = '3'
  1748           }
  1749           break
  1750         }
  1751       }
  1752       if(nodeInfo) {
  1753         info.javaTronVersion = nodeInfo.configNodeInfo.codeVersion
  1754       }
  1755     } catch (err) {
  1756     }
  1757     return Promise.resolve(info)
  1758   }

i do not know ........
``````

**Comment by yanwankun** [comment]
I have solved this problem, it seems that tronbox can not be used on centos, I switched to ubuntu, and now I can deploy my contract.
